name: Download static site
description: Download the static-site build artifact from the quality job

runs:
  using: composite
  steps:
    - name: Download build artifact
      uses: actions/download-artifact@d3f86a106a0bac45b974a628896c90dbdf5c8093 # v4
      with:
        name: static-site
        path: out/
